# Generated by Django 4.2.9 on 2024-08-19 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_rename_post_comment_post_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
